language: cpp
sudo: false
dist: focal

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

services:
  - docker

compiler:
  - gcc

env:
  global:
    - IMAGE_NAME=willallves/grpc-build:1.34.0
    - CONTAINER_NAME=cspiffe

before_script:
  - docker pull "$IMAGE_NAME"
  - docker run -d --name "$CONTAINER_NAME" "$IMAGE_NAME" ./init-server.sh
  - docker cp . "$CONTAINER_NAME":/mnt
    
script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - docker exec "$CONTAINER_NAME" mkdir -p /mnt/build
  - docker exec -w /mnt/build "$CONTAINER_NAME" cmake ..
  - docker exec -w /mnt/build "$CONTAINER_NAME" make
  - docker exec -w /mnt/build "$CONTAINER_NAME" make test
