codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2      # Number of decimal places, between 0 and 5
  round: down       # up, down, or nearest
  range: "60...90"  # First number represents red, and second represents green
                    # (default is 70..100)
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
