#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: '3'
services:
  spire-server:
  workload:
  tests:
    volumes:
      - ../integration_test/:/mnt/c-spiffe/integration_test/
