#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: '3'
services:
  spire-server:
    image: alg4/infra_spire-server
    hostname: spire-server
    tty: true
    ports:
      - "8081:8081"
  
  spire-server2:
    image: alg4/infra_spire-server
    hostname: spire-server2
    tty: true
    ports:
      - "9090:9090"

  workload:
    image: alg4/infra_workload
    tty: true
    hostname: workload
    links:
      - spire-server
      - spire-server2
    ports:
      - "4433:4433"
      - "443:443"

  workload2:
    image: alg4/infra_workload
    tty: true
    hostname: workload2
    links:
      - spire-server
      - spire-server2
    ports:
      - "4434:4434"

  # Todo: Create sceneries for spire-server test; script python; "getRequestor" {generate, get, (entrys, token)}
  tests:
    image: alg4/infra_tests
    tty: true
    hostname: tests
    links:
      - spire-server
      - spire-server2
      - workload
