#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: '3'
services:
  spire-server:
  spire-server2:
  workload:
    volumes: 
      - ..:/mnt/c-spiffe
  workload2:
    volumes: 
    - ..:/mnt/c-spiffe
  tests:
    volumes: 
    - ..:/mnt/c-spiffe