# (C) Copyright 2020-2021 Hewlett Packard Enterprise Development LP
#
# 
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# 
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# 
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: '3'
services:
  spire-server:
    image: cspiffe/spire-server
    hostname: spire-server
    tty: true
    ports:
      - "8081:8081"
  
  spire-server2:
    image: cspiffe/spire-server
    hostname: spire-server2
    tty: true
    ports:
      - "9090:9090"

  workload:
    image: cspiffe/workload:${TAG}
    tty: true
    hostname: workload
    links:
      - spire-server
      - spire-server2
    ports:
      - "4433:4433"
      - "443:443"


  workload2:
    image: cspiffe/workload:${TAG}
    tty: true
    hostname: workload2
    links:
      - spire-server
      - spire-server2
    ports:
      - "4434:4434"


  tests:
    image: cspiffe/tests:${TAG}
    tty: true
    hostname: tests
    links:
      - spire-server
      - spire-server2
      - workload
      - workload2
