#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: '3'
services:
  spire-server:
  workload:
  tests:
  # For tests
  # spiffetls-test:
  #   volumes:
  #     - "../../c-spiffe:/mnt/"
