#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: '3'
services:
  spire-server:
    image: cspiffe/spire-server
    hostname: spire-server
    tty: true
    ports:
      - "8081:8081"
  
  spire-server2:
    image: cspiffe/spire-server
    hostname: spire-server2
    tty: true
    ports:
      - "9090:9090"

  workload:
    image: cspiffe/workload:${TAG}
    tty: true
    hostname: workload
    links:
      - spire-server
      - spire-server2
    ports:
      - "4433:4433"
      - "443:443"


  workload2:
    image: cspiffe/workload:${TAG}
    tty: true
    hostname: workload2
    links:
      - spire-server
      - spire-server2
    ports:
      - "4434:4434"


  tests:
    image: cspiffe/tests:${TAG}
    tty: true
    hostname: tests
    links:
      - spire-server
      - spire-server2
      - workload
      - workload2
