name: Build and run tests

on: push

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    container:
      image: willallves/grpc-build:1.34.0
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Log the parent container ubuntu version
        run: lsb_release -a

      - name: Create Build Environment
        shell: bash
        run: mkdir build
      
      - name: Configure CMake
        shell: bash
        run: cd build && cmake ..
      
      - name: Build
        shell: bash
        run:  cd build && make
      
      - name: Unit Testing
        shell: bash
        run: cd build && make test

      - name: Coverage Test
        shell: bash
        run: cd build && make gcov && make lcov && lcov --list Coverage/lcov.info

      - name: Integration Test
        shell: bash
        run: cd integration_test && behave --tags=-@wip

      - name: Test coverage codecov
        shell: bash
        run: bash <(curl -s https://codecov.io/bash) 
