name: Build and run tests

on: push

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    container:
      image: willallves/grpc-build:1.34.0
    steps:
      -
        name: Checkout Project
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build & push Docker image
        uses: docker/build-push-action@v1
        with:
          dockerfile: docker/test.Dockerfile
          repository:  willallves/grpc-build
          tag_with_ref: true
