name: Build and run tests

on: push

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    container:
      image: willallves/grpc-build:1.34.0
    steps:
      - name: Log the parent container grpc version
        run: |
          lsb_release -a
        # Echo the ubuntu version of the parent container
