name: Create a Release
on: 
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      HAS_TOKEN: ${{ secrets.TOKEN_GITHUB != '' }}

    steps:
    - name: Checkout public repository
      uses: actions/checkout@v2

    - name: Create tag
      if: ${{ env.HAS_TOKEN == 'true' }}
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        GITHUB_TOKEN: "${{ secrets.TOKEN_GITHUB }}"
        tag_prefix: "v"

    - name: Create Release
      if: ${{ env.HAS_TOKEN == 'true' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
