name: Create a Release
on: 
  pull_request_target:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repository
      uses: actions/checkout@v2

    - name: Create tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
