name: Release Build
on: push

jobs:
  build:
    Release Build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          # GH_REPO is required for older releases of `gh`. Until we're
          # reasonably confident that that the gh release is new enough,
          # set GH_REPO to the repository to create the release in.
          #
          # See https://github.com/cli/cli/issues/3556
          GH_REPO: ${{ github.repository }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Create the release against the annotated tag. The GITHUB_REF envvar
        # includes the "refs/tags" prefix, which is fine to pass to `gh release
        # create` for the reference to create the release from. However we
        # strip off the prefix to give the release a nice title with just the
        # version number.
        #
        # See https://docs.github.com/en/actions/reference/environment-variables.
        run: gh release create "${GITHUB_REF}" ./artifacts/*.tar.gz ./artifacts/*.txt --title "${GITHUB_REF#refs/tags/}"
